[package]
name = "CSC-411-Assignment-1"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = { version = "0.9.2", features = ["small_rng"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
